kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: image-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: coe-netapp-nas
