kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: bschmeli@redhat.com
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: stormshift-admins
  - kind: ServiceAccount
    name: automation
    namespace: stormshift
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
