apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: coe-netapp-nas
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
  provisioningType: "thin"
  snapshots: "true"
