apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: virt-node
  name: 56-virt-node-disable-hyperthreading
spec:
  config:
    ignition:
      version: 3.2.0
  kernelArguments:
    - nosmt
