---
apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  name: kubevirt-hyperconverged
  namespace: openshift-cnv
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  featureGates:
    enableCommonBootImageImport: true
    deployTektonTaskResources: true
    VMPersistentState: true
# For vmStateStorage, we need to use cephfs because netapp cant do 12MB PVCs:
  vmStateStorageClass: ocs-storagecluster-cephfs
