apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: coe-bridge-via-enp4s0f1
  annotations:
    argocd.argoproj.io/sync-wave: '100'
spec:
  desiredState:
    interfaces:
    - bridge:
        options:
          stp:
            enabled: false
        port:
        - name: enp4s0f1
      description: Linux Brige info COE Network via enp4s0f1
      ipv4:
        enabled: false
      name: coe-bridge
      state: up
      type: linux-bridge

    - name: enp4s0f1.69
      description: coe-air-gapped-vlan
      type: vlan
      state: absent
      ipv4:
        enabled: false
      vlan:
        base-iface: enp4s0f1
        id: 69

    - bridge:
        options:
          stp:
            enabled: false
        port:
        - name: enp4s0f1.69
      description: Linux Brige info COE Network via enp4s0f1
      ipv4:
        enabled: false
      name: coe-br-vlan-69
      state: absent
      type: linux-bridge


  nodeSelector:
    coe.muc.redhat.com/second-nic: enp4s0f1