kind: MultiClusterObservability
apiVersion: observability.open-cluster-management.io/v1beta2
metadata:
  name: observability
  namespace: open-cluster-management-observability
spec:
  imagePullPolicy: IfNotPresent
  imagePullSecret: multiclusterhub-operator-pull-secret
  observabilityAddonSpec: # The ObservabilityAddonSpec defines the global settings for all managed clusters which have observability add-on enabled
    enableMetrics: true # EnableMetrics indicates the observability addon push metrics to hub server
    interval: 60 # Interval for the observability addon push metrics to hub server
  enableDownSampling: true
  advanced:
    retentionConfig:
      retentionInLocal: 48h
      retentionResolutionRaw: 30d
      retentionResolution5m: 180d
      retentionResolution1h: 365d
    receive:
      resources:
        limits:
          memory: 2Gi
      replicas: 3
  storageConfig: # Specifies the storage to be used by Observability
    metricObjectStorage:
      name: thanos-object-storage
      key: thanos.yaml
    compactStorageSize: 10Gi
    receiveStorageSize: 10Gi
    ruleStorageSize: 1Gi
    storeStorageSize: 10 Gi
    storageClass: coe-netapp-san
