apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-windows-vms
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: './'
    repoURL: ssh://git@gitlab.consulting.redhat.com:2222/coe-lab/examples-windows-vms.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
