apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: virt-node
spec:
  machineConfigSelector:
    matchExpressions:
      - {key: machineconfiguration.openshift.io/role, operator: In, values: [worker,virt-node]}
  maxUnavailable: 2
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/virt-node: ""
  paused: false
