apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
  annotations:
    argocd.argoproj.io/sync-wave: '-5'
  name: cloudnative-pg
  namespace: openshift-operators
spec:
  channel: stable-v1
  installPlanApproval: Manual
  name: cloudnative-pg
  source: certified-operators
  sourceNamespace: openshift-marketplace
